### ISSUE TITLE
OOP Notes Feedback

### ISSUE THREAD

**Issue by cooper-mj** [stanfordpython/course-reader#11]
Overall, these are fantastic!! Feedback in roughly chronological order; line numbers referenced for convenience.

- Line 223: We already cover mutable and immutable objects in the functions notes. This is good as a refresher, but it might be useful to add, "Recall," or something to signal that our treatment of mutable and immutable objects here is review. Actually... this treatment gets extended somewhat. Let's resolve in person and discuss whether this belongs here vs. at the beginning of the functions notes (before discussing how Python passes objects).
- Line 429: Here, define private/public for people who may not have seen them (people _should_ have from CS106A/B, but it might be a useful refresher). Also, a quick explanation of how Python changes the name of the "super secret" variables, in addition to the example, would be helpful.
- Line 474: Double equals here?
- Line 539: Perhaps give some intuition here for why we're trying to bind to the class instance, rather than just a "let's see what happens"?
- Line 568: Here, consider mentioning that Python builtins are commonly preceded and succeeded by a double underscore.
- Line 592: Consider referencing `Point` with the code typesetting so it's extra clear we're referring to objects of type `Point` here.
- Line 647: The inheritance section could use a slightly more real-world example. Maybe we can even use the `StanfordClass` and `StanfordCSClass` classes from the lab as an example here? My thinking is that it would be nice here to have an example that not only showcases inheritance, but also does so in a way that feels relevant to students. The current `Parent`/`Child` example feels somewhat abstract.
- Line 685 through to the end: This is neat but... after reading this section it's quite unclear to me why this is important. There are three main ambiguities which I'm left with at the end of this section: (1) Why does it matter that exceptions are classes that inherit from each other? If the answer is "we just talked about exceptions so it's relevant," this becomes somewhat circular, as part of the motivation for discussing exceptions in this set of notes (as opposed to elsewhere) was so that we could discuss exception inheritance. (2) More importantly, if I am to write a new exception, of what benefit is it to have it inherit from the best fitting subclass rather than just from `BaseException` or `Exception`? (3) To follow up (2), if exceptions are classes, I'm left with the sense that I've been told an interesting fact (that exceptions are classes, and inherit) without sufficient information to understand it deeply. What types of methods do exceptions contain? What do those methods do? As a student here, I'd be very curious to do a shallow-dive into exception implementation to see how it fits into the discussion of classes from earlier in this notes section.

**Comment by parthsarin** [comment]
Thanks for your feedback, Michael!

* Line 474: I intentionally used a single equals to separate this from Python-world. That's also how we did it in the notes. Alternatively, I could use the squiggly equals sign (≈).
* Line 647: I honestly don't think that `StanfordClass` and `StanfordCSClass` would be that much more relevant to students, especially since we're only showing how to overwrite a variable declared in the parent... I gave it my best shot, though!
* Line 685 to the end: To address your comments, (1) it's mostly for diagnosing them when they're raised, (2) so that when certain classes are caught, your exception won't be accidentally caught... if I'm catching `KeyError`s, your exception shouldn't inherit from `KeyError` unless it's actually a `KeyError`. I allude to this now: let me know if I need to make it more concrete, (3) I gave an example.

**Comment by parthsarin** [comment]
Thanks for your feedback, Michael!

> * Line 474: Double equals here?

I intentionally used a single equals to separate this from Python-world. That's also how we did it in the notes. Alternatively, I could use the squiggly equals sign (≈).

> * Line 647: The inheritance section could use a slightly more real-world example. Maybe we can even use the `StanfordClass` and `StanfordCSClass` classes from the lab as an example here? My thinking is that it would be nice here to have an example that not only showcases inheritance, but also does so in a way that feels relevant to students. The current `Parent`/`Child` example feels somewhat abstract.

I honestly don't think that `StanfordClass` and `StanfordCSClass` would be that much more relevant to students, especially since we're only showing how to overwrite a variable declared in the parent... I gave it my best shot, though!

> * Line 685 through to the end: This is neat but... after reading this section it's quite unclear to me why this is important. There are three main ambiguities which I'm left with at the end of this section: (1) Why does it matter that exceptions are classes that inherit from each other? If the answer is "we just talked about exceptions so it's relevant," this becomes somewhat circular, as part of the motivation for discussing exceptions in this set of notes (as opposed to elsewhere) was so that we could discuss exception inheritance. (2) More importantly, if I am to write a new exception, of what benefit is it to have it inherit from the best fitting subclass rather than just from `BaseException` or `Exception`? (3) To follow up (2), if exceptions are classes, I'm left with the sense that I've been told an interesting fact (that exceptions are classes, and inherit) without sufficient information to understand it deeply. What types of methods do exceptions contain? What do those methods do? As a student here, I'd be very curious to do a shallow-dive into exception implementation to see how it fits into the discussion of classes from earlier in this notes section.

1. It's mostly for diagnosing them when they're raised.
2. So that when certain classes are caught, your exception won't be accidentally caught... if I'm catching `KeyError`s, your exception shouldn't inherit from `KeyError` unless it's actually a `KeyError`. I allude to this now: let me know if I need to make it more concrete
3. I gave an example in the commit.

**Comment by cooper-mj** [comment]
Fantastic - I love the changes and I agree with the points in your above comment. Closing the issue. 😊
